"""Data preparation tools used by Agent 2.

Each function is a single, testable operation. Agent 2's LLM
reads the cleaning_plan generated by Agent 1 and dispatches to
these functions — keeping logic reusable and the agent dynamic.
"""
from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


# ── Individual operations ─────────────────────────────────────────────────────

def impute_column(
    df: pd.DataFrame,
    column: str,
    strategy: str,
    fill_value: Any = None,
) -> pd.DataFrame:
    """Impute missing values in *column* using *strategy*.

    Strategies: mean | median | mode | constant | ffill | bfill | drop_rows
    """
    if column not in df.columns:
        logger.warning("impute_column: '%s' not found — skipped.", column)
        return df

    if strategy == "mean":
        df[column] = df[column].fillna(df[column].mean())
    elif strategy == "median":
        df[column] = df[column].fillna(df[column].median())
    elif strategy == "mode":
        mode = df[column].mode()
        df[column] = df[column].fillna(mode.iloc[0] if not mode.empty else np.nan)
    elif strategy == "constant":
        df[column] = df[column].fillna(fill_value)
    elif strategy == "ffill":
        df[column] = df[column].ffill()
    elif strategy == "bfill":
        df[column] = df[column].bfill()
    elif strategy == "drop_rows":
        df = df.dropna(subset=[column])
    else:
        logger.warning("impute_column: unknown strategy '%s' — skipped.", strategy)
    return df


def remove_duplicates(df: pd.DataFrame, subset: Optional[List[str]] = None) -> pd.DataFrame:
    """Remove exact duplicate rows."""
    before = len(df)
    df = df.drop_duplicates(subset=subset, keep="first")
    logger.info("remove_duplicates: removed %d rows.", before - len(df))
    return df


def cap_outliers(
    df: pd.DataFrame,
    column: str,
    method: str = "iqr",
    lower_pct: float = 0.01,
    upper_pct: float = 0.99,
) -> pd.DataFrame:
    """Cap outliers using IQR fences or percentile clipping.

    Methods: iqr | percentile
    """
    if column not in df.columns:
        logger.warning("cap_outliers: '%s' not found — skipped.", column)
        return df

    s = pd.to_numeric(df[column], errors="coerce")
    if method == "iqr":
        q1, q3 = s.quantile(0.25), s.quantile(0.75)
        iqr = q3 - q1
        lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr
    else:  # percentile
        lo, hi = s.quantile(lower_pct), s.quantile(upper_pct)

    df[column] = s.clip(lower=lo, upper=hi)
    logger.info("cap_outliers: '%s' capped to [%s, %s].", column, lo, hi)
    return df


def flag_outliers(df: pd.DataFrame, column: str) -> pd.DataFrame:
    """Add a boolean flag column instead of removing outliers."""
    if column not in df.columns:
        return df
    s = pd.to_numeric(df[column], errors="coerce")
    q1, q3 = s.quantile(0.25), s.quantile(0.75)
    iqr = q3 - q1
    flag_col = f"{column}_outlier_flag"
    df[flag_col] = ((s < q1 - 1.5 * iqr) | (s > q3 + 1.5 * iqr)).astype(int)
    return df


def correct_dtype(df: pd.DataFrame, column: str, target_type: str) -> pd.DataFrame:
    """Cast *column* to the target pandas dtype."""
    type_map = {
        "numeric": lambda s: pd.to_numeric(s, errors="coerce"),
        "datetime": lambda s: pd.to_datetime(s, errors="coerce"),
        "string": lambda s: s.astype(str),
        "category": lambda s: s.astype("category"),
        "boolean": lambda s: s.astype(bool),
    }
    if column not in df.columns or target_type not in type_map:
        logger.warning("correct_dtype: cannot cast '%s' to '%s'.", column, target_type)
        return df
    df[column] = type_map[target_type](df[column])
    return df


def standardize_categorical(df: pd.DataFrame, column: str) -> pd.DataFrame:
    """Lowercase-strip all string values in a categorical column."""
    if column not in df.columns:
        return df
    df[column] = df[column].astype(str).str.lower().str.strip()
    return df


def drop_column(df: pd.DataFrame, column: str) -> pd.DataFrame:
    """Drop a column from the DataFrame."""
    if column in df.columns:
        df = df.drop(columns=[column])
        logger.info("drop_column: dropped '%s'.", column)
    return df


# ── Plan executor ─────────────────────────────────────────────────────────────

_ACTION_MAP = {
    "impute": lambda df, step: impute_column(
        df,
        step["column"],
        step.get("strategy", "median"),
        step.get("fill_value"),
    ),
    "remove_duplicates": lambda df, step: remove_duplicates(
        df, step.get("subset")
    ),
    "cap_outliers": lambda df, step: cap_outliers(
        df,
        step["column"],
        step.get("method", "iqr"),
    ),
    "flag_outliers": lambda df, step: flag_outliers(df, step["column"]),
    "correct_dtype": lambda df, step: correct_dtype(
        df, step["column"], step.get("target_type", "numeric")
    ),
    "standardize_categorical": lambda df, step: standardize_categorical(
        df, step["column"]
    ),
    "drop_column": lambda df, step: drop_column(df, step["column"]),
}


def execute_cleaning_plan(df: pd.DataFrame, cleaning_plan: List[Dict]) -> tuple[pd.DataFrame, List[Dict]]:
    """Execute every step in the LLM-generated cleaning plan.

    Returns the cleaned DataFrame and an execution log.
    """
    log = []
    # Sort by priority if present
    plan = sorted(cleaning_plan, key=lambda x: x.get("priority", 99))

    for step in plan:
        action = step.get("action", "").lower()
        handler = _ACTION_MAP.get(action)
        if handler is None:
            log.append({"step": step, "status": "skipped", "reason": f"Unknown action '{action}'"})
            continue
        try:
            df = handler(df, step)
            log.append({"step": step, "status": "applied"})
        except Exception as exc:
            log.append({"step": step, "status": "error", "reason": str(exc)})
            logger.error("execute_cleaning_plan: step %s failed — %s", step, exc)

    return df, log
